cart/urls.py
from django.urls import path
from .views import (add_to_cart, remove_from_cart, order_view, checkout)


app_name = 'cart'

urlpatterns = [
    path('add-to-cart/<book_slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<book_slug>/',
         remove_from_cart, name='remove-from-cart'),
    path('order-summary/',
         order_view, name='order-summary'),
    path('checkout/', checkout, name='checkout')
]

django_marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_profile.views import profile_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('', include('main.urls')),
    path('account/profile/', profile_view, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings. MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'books'

urlpatterns = [
    path('', book_list, name='book-list'),
    path('<slug>/', book_detail, name='book-detail'),
    path('<book_slug>/<int:chapter_number>',
         chapter_detail, name='chapter-detail'),
    path('<book_slug>/<int:chapter_number>/<int:exercise_number>/',
         exercise_detail, name='exercise-detail')
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from main.models import Book

# Create your models here.


class OrderItem(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.book.title


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    ref_code = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        return self.items.all().aggregate(order_total=Sum('book__price'))['order_total']


class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    total_amount = models.FloatField()
    date_paid = models.DateTimeField(auto_now_add=True)
    stripe_charge_id = models.CharField(max_length=100)

    def __str__(self):
        return self.stripe_charge_id

cart/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404
from main.models import Book
from .models import Order, OrderItem, Payment
from django.conf import settings
import stripe
import random
import string

# Create your views here.

stripe.api_key = settings.STRIPE_SECRET_KEY


def create_ref_code():
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=15))


@login_required
def add_to_cart(request, book_slug):
    book = get_object_or_404(Book, slug=book_slug)
    order_item, created = OrderItem.objects.get_or_create(book=book)
    order, created = Order.objects.get_or_create(
        user=request.user, is_ordered=False)
    order.items.add(order_item)
    order.save()
    messages.info(request, "Item successfully added to your cart.")
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required
def remove_from_cart(request, book_slug):
    book = get_object_or_404(Book, slug=book_slug)
    order_item = get_object_or_404(OrderItem, book=book)
    order = Order.objects.get(user=request.user, is_ordered=False)
    order.items.remove(order_item)
    order.save()
    messages.info(request, "Item successfully removed from your cart.")
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required
def order_view(request):
    order_qs = Order.objects.filter(user=request.user, is_ordered=False)
    if order_qs.exists():
        context = {
            'order': order_qs[0]
        }
        return render(request, "cart/order_summary.html", context)
    return Http404


@login_required
def checkout(request):
    order_qs = Order.objects.filter(user=request.user, is_ordered=False)
    if order_qs.exists():
        order = order_qs[0]
    else:
        return Http404
    if request.method == "POST":
        # complete order
        order.ref_code = create_ref_code()

        # create stripe charge
        token = request.POST.get('stripeToken')
        charge = stripe.Charge.create(
            amount=int(order.get_total() * 75.90),  # cents
            currency="inr",
            source=token,
            description="Charge for {}".format(request.user.username),
        )

        # create payment object link to the order
        payment = Payment()
        payment.order = order
        payment.stripe_charge_id = charge.id
        payment.total_amount = order.get_total()
        payment.save()

        # add book to the users available books
        books = [item.book for item in order.items.all()]
        for book in books:
            request.user.userlibrary.books.add(book)

        order.is_ordered = True
        order.save()

        # redirect to user profile

        messages.success(request, "Your order was successfully placed")

        return redirect('/account/profile/')

    context = {
        'order': order,
    }

    return render(request, "cart/checkout.html", context)

cart/templates/cart/checkout.html
{% extends 'main_base.html' %}
{% load static %} 
{% block head_css_site %}

<link href="{% static 'css/stripe.css' %}" rel="stylesheet" type="text/css">

{% endblock head_css_site %}

{% block content %}

<h1>Checkout</h1>
<hr>

    <p class="pull-right">Order total: ${{ order.get_total }}</p>

    <script src="https://js.stripe.com/v3/"></script>

    <form action="{% url 'cart:checkout' %}" method="post" id="payment-form">
    {% csrf_token %}
        <div class="stripe-form-row">
            <label for="card-element" class="stripe-label">
            Credit or debit card
            </label>
            <div id="card-element">
            <!-- A Stripe Element will be inserted here. -->
            </div>

            <!-- Used to display form errors. -->
            <div id="card-errors" role="alert"></div>
        </div>

        <button class="stripe-button">Submit Payment</button>
    </form>

    <script src="{% static 'js/stripe.js' %}"></script>

{% endblock content %}

cart/templates/cart/order_summary.html
{% extends 'main_base.html' %}

{% block content %}

<h1>Order Summary<h1>
<hr>

<table class="table table-hover table-bordered text-center">
    <tr class="text-center">
        <th>no.</th>
        <th>Title</th>
        <th>Price</th>
    </tr>
    {% for item in order.items.all %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ item.book.title }}
            <span><a href="{% url 'cart:remove-from-cart' item.book.slug %}" class="text-danger"><i class='fa fa-trash'></i></a></span>
            </td>
            <td>${{ item.book.price }}</td>
        <tr>
    {% empty %}
        <tr>
        <td colspan="3">
            There are no items in your cart
        </td>
        </tr>
    {% endfor %}
    {% if order.get_total %}
    <tr>
    <td colspan="2">
        <strong class="pull-right">Order total: </strong>
    </td>
    <td colspan="1">
        <strong>${{ order.get_total }}</strong>
    </td>
    </tr>
    {% endif %}
    <tr>
        <td colspan="3">
            <a href="{% url 'books:book-list' %}" class="btn btn-warning">
            {% if order %}
                Continue shopping
            {% else %}
                Add items to your cart
            {% endif %}
            </a>
        </td>
    </tr>
    {% if order.get_total %}
    <tr>
        <td colspan="3">
            <a href="{% url 'cart:checkout' %}" class="btn btn-success">
                Checkout
            </a>
        </td>
    </tr>
    {% endif %}
</table>

{% endblock content %}