cart/urls.py
from django.urls import path
from .views import (add_to_cart, remove_from_cart, order_view, checkout)


app_name = 'cart'

urlpatterns = [
    path('add-to-cart/<book_slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<book_slug>/',
         remove_from_cart, name='remove-from-cart'),
    path('order-summary/',
         order_view, name='order-summary'),
    path('checkout/', checkout, name='checkout')
]

django_marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_profile.views import profile_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('', include('main.urls')),
    path('account/profile/', profile_view, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings. MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'books'

urlpatterns = [
    path('', book_list, name='book-list'),
    path('<slug>/', book_detail, name='book-detail'),
    path('<book_slug>/<int:chapter_number>',
         chapter_detail, name='chapter-detail'),
    path('<book_slug>/<int:chapter_number>/<int:exercise_number>/',
         exercise_detail, name='exercise-detail')
]

main/models.py
from django.db import models
from django.shortcuts import redirect, reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.


class UserLibrary(models.Model):
    books = models.ManyToManyField('Book', blank=True)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def book_list(self):
        return self.books.all()

    class Meta:
        verbose_name = 'User Library'
        verbose_name_plural = 'User Library'


def post_user_signup_reciever(sender, instance, created, *args, **kwargs):
    if created:
        UserLibrary.objects.get_or_create(user=instance)


post_save.connect(post_user_signup_reciever, sender=User)


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    slug = models.SlugField()

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class Book(models.Model):
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=100)
    publication = models.DateTimeField()
    isbn = models.CharField(max_length=16)
    slug = models.SlugField()
    cover = models.ImageField()
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book-detail", kwargs={
            'slug': self.slug
        })


class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:chapter-detail", kwargs={
            'book_slug': self.book.slug,
            'chapter_number': self.chapter_number
        })


class Exercise(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    exercise_number = models.IntegerField()
    page_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:exercise-detail", kwargs={
            'book_slug': self.chapter.book.slug,
            'chapter_number': self.chapter.chapter_number,
            'exercise_number': self.exercise_number
        })


class Solution(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    solution_number = models.IntegerField()
    image = models.ImageField()

    def __str__(self):
        return "{}-{}".format(self.exercise, self.pk)

main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import *
from cart.models import Order, OrderItem, Payment

# Create your views here.
OWNED = 'owned'
IN_CART = 'in_cart'
NOT_IN_CART = 'not_in_cart'


def check_book_relationship(request, book):
    if book in request.user.userlibrary.books.all():
        return OWNED
    order_qs = Order.objects.filter(user=request.user, is_ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        order_item_qs = OrderItem.objects.filter(book=book)
        if order_item_qs.exists():
            order_item = order_item_qs[0]
            if order_item in order.items.all():
                return IN_CART
    return NOT_IN_CART


def book_list(request):
    queryset = Book.objects.all()
    context = {
        'queryset': queryset
    }
    return render(request, 'main/book_list.html', context)


@login_required
def book_detail(request, slug):
    book = get_object_or_404(Book, slug=slug)
    book_status = check_book_relationship(request, book)
    context = {
        'book': book,
        'book_status': book_status
    }
    return render(request, 'main/book_detail.html', context)


@login_required
def chapter_detail(request, book_slug, chapter_number):
    chapter_qs = Chapter.objects.filter(
        book__slug=book_slug).filter(chapter_number=chapter_number)
    chapter = chapter_qs[0]
    book_status = check_book_relationship(request, chapter.book)
    if chapter_qs.exists():
        context = {
            'chapter': chapter_qs[0],
            'book_status': book_status
        }
        return render(request, 'main/chapter_detail.html', context)
    return Http404


@login_required
def exercise_detail(request, book_slug, chapter_number, exercise_number):
    exercise_qs = Exercise.objects.filter(
        chapter__book__slug=book_slug).filter(chapter__chapter_number=chapter_number).filter(exercise_number=exercise_number)
    exercise = exercise_qs[0]
    book_status = check_book_relationship(request, exercise.chapter.book)
    if exercise_qs.exists():
        context = {
            'exercise': exercise_qs[0],
            'book_status': book_status
        }
        return render(request, 'main/exercise_detail.html', context)
    return Http404

main/templates/main/book_detail.html
{% extends 'main_base.html' %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item" aria-current="page"><a href="{% url 'books:book-list' %}">Available Books</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ book.title }}</li>
    </ol>
</nav>
{% endblock breadcrumb %}

{% block content %}

    <div class="row">

    <main class="col-md-4">
        {% include 'book_snippet.html' with book=book %}
    </main>

    <aside class="col-md-8">
        <div class="card">
            <div class="card-header">
                Chapters
            </div>
            <ul class="list-group list-group-flush">
                {% for chapter in book.chapter_set.all %}
                <li class="list-group-item"><a href="{{ chapter.get_absolute_url }}">{{ chapter.chapter_number }}.{{ chapter.title }} </a></li>
                {% endfor %}
            </ul>
        </div>
    </aside>

    </div>

{% endblock content %}

main/templates/main/book_list.html
{% extends 'main_base.html' %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Available Books</li>
    </ol>
</nav>
{% endblock breadcrumb %}

{% block content %}
<h3> View Available Books </h3>
<div class="row display-flex-row justify-content-between">
{% for book in queryset %}
    <div class="card shadow-lg col-3 mr-1 mb-3 mt-2" style="width: 18rem;">
        <img src="{{ book.cover.url }}" class="card-img-top" alt="..." height="350px">
        <div class="card-body">
            <h5 class="card-title">{{ book.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted"> {{ book.publication }} </h6>
            <p class="card-text">
            {% for author in book.authors.all %}
                <span>{{ author }}</span>
                {% if book.authors.count > 1 %} | {% endif %}
            {% endfor %}
            </p>
            <a href="{{ book.get_absolute_url }}" class="card-link">{{ book }}</a>
        </div>
    </div>
{% endfor %}
</div>
{% endblock content %}

main/templates/main/chapter_detail.html
{% extends 'main_base.html' %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item" aria-current="page"><a href="{% url 'books:book-list' %}">Available Books</a></li>
        <li class="breadcrumb-item" aria-current="page"><a href="{{ chapter.book.get_absolute_url }}">{{ chapter.book.title }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ chapter }}</li>
    </ol>
</nav>
{% endblock breadcrumb %}

{% block content %}

    <div class="row">

    <main class="col-md-4">
        {% include 'book_snippet.html' with book=chapter.book %}
    </main>

    <aside class="col-md-8">
        <div class="card">
            <div class="card-header">
                Exercises
            </div>
            <ul class="list-group list-group-flush">
                {% for exercise in chapter.exercise_set.all %}
                <li class="list-group-item"><a href="{{ exercise.get_absolute_url }}">{{ exercise.exercise_number }}.{{ exercise.title }} </a></li>
                {% endfor %}
            </ul>
        </div>
    </aside>

    </div>
{% endblock content %}

main/templates/main/exercise_detail.html
{% extends 'main_base.html' %}
{% load static %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item" aria-current="page"><a href="{% url 'books:book-list' %}">Available Books</a></li>
        <li class="breadcrumb-item" aria-current="page"><a href="{{ exercise.chapter.book.get_absolute_url }}">{{ exercise.chapter.book.title }}</a></li>
        <li class="breadcrumb-item" aria-current="page"><a href="{{ exercise.chapter.get_absolute_url }}">{{ exercise.chapter.title }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ exercise.title }}</li>
    </ol>
</nav>
{% endblock breadcrumb %}

{% block content %}
    <div class="row">

    <main class="col-md-4">
        {% include 'book_snippet.html' with book=exercise.chapter.book %}
    </main>

    <aside class="col-md-8">
        <div class="card">
            <div class="card-header">
                Solutions
            </div>

            {% if book_status == 'owned' %}

            {% for solution in exercise.solution_set.all %}
                <div class="accordion" id="toggle-{{ solution.solution_number }}">
                    <div class="card">
                        <div class="card-header" id="heading-{{ solution.solution_number }}">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse-{{ solution.solution_number }}" aria-expanded="true" aria-controls="collapse-{{ solution.solution_number }}">
                                Solution {{ solution.solution_number }}
                            </button>
                        </h2>
                        </div>

                        <div id="collapse-{{ solution.solution_number }}" class="collapse" aria-labelledby="heading-{{ solution.solution_number }}" data-parent="#toggle-{{ solution.solution_number }}">
                        <div class="card-body">
                            <img src="{{ solution.image.url }}" style="width: 100%">
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% else %}
            <div class="text-center">
                <h4>You do not have access to this book.<a href="#">Purchase this book</a></h4>
                <img src="{% static 'images/lock.png' %}" />
            </div>
            {% endif %}
        </div>
    </aside>

    </div>
{% endblock content %}