cart/urls.py
from django.urls import path
from .views import (add_to_cart, remove_from_cart, order_view, checkout)


app_name = 'cart'

urlpatterns = [
    path('add-to-cart/<book_slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<book_slug>/',
         remove_from_cart, name='remove-from-cart'),
    path('order-summary/',
         order_view, name='order-summary'),
    path('checkout/', checkout, name='checkout')
]

django_marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_profile.views import profile_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('', include('main.urls')),
    path('account/profile/', profile_view, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings. MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'books'

urlpatterns = [
    path('', book_list, name='book-list'),
    path('<slug>/', book_detail, name='book-detail'),
    path('<book_slug>/<int:chapter_number>',
         chapter_detail, name='chapter-detail'),
    path('<book_slug>/<int:chapter_number>/<int:exercise_number>/',
         exercise_detail, name='exercise-detail')
]

main/models.py
from django.db import models
from django.shortcuts import redirect, reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.


class UserLibrary(models.Model):
    books = models.ManyToManyField('Book', blank=True)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def book_list(self):
        return self.books.all()

    class Meta:
        verbose_name = 'User Library'
        verbose_name_plural = 'User Library'


def post_user_signup_reciever(sender, instance, created, *args, **kwargs):
    if created:
        UserLibrary.objects.get_or_create(user=instance)


post_save.connect(post_user_signup_reciever, sender=User)


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    slug = models.SlugField()

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class Book(models.Model):
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=100)
    publication = models.DateTimeField()
    isbn = models.CharField(max_length=16)
    slug = models.SlugField()
    cover = models.ImageField()
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book-detail", kwargs={
            'slug': self.slug
        })


class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:chapter-detail", kwargs={
            'book_slug': self.book.slug,
            'chapter_number': self.chapter_number
        })


class Exercise(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    exercise_number = models.IntegerField()
    page_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:exercise-detail", kwargs={
            'book_slug': self.chapter.book.slug,
            'chapter_number': self.chapter.chapter_number,
            'exercise_number': self.exercise_number
        })


class Solution(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    solution_number = models.IntegerField()
    image = models.ImageField()

    def __str__(self):
        return "{}-{}".format(self.exercise, self.pk)

main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import *
from cart.models import Order, OrderItem, Payment

# Create your views here.
OWNED = 'owned'
IN_CART = 'in_cart'
NOT_IN_CART = 'not_in_cart'


def check_book_relationship(request, book):
    if book in request.user.userlibrary.books.all():
        return OWNED
    order_qs = Order.objects.filter(user=request.user, is_ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        order_item_qs = OrderItem.objects.filter(book=book)
        if order_item_qs.exists():
            order_item = order_item_qs[0]
            if order_item in order.items.all():
                return IN_CART
    return NOT_IN_CART


def book_list(request):
    queryset = Book.objects.all()
    context = {
        'queryset': queryset
    }
    return render(request, 'main/book_list.html', context)


@login_required
def book_detail(request, slug):
    book = get_object_or_404(Book, slug=slug)
    book_status = check_book_relationship(request, book)
    context = {
        'book': book,
        'book_status': book_status
    }
    return render(request, 'main/book_detail.html', context)


@login_required
def chapter_detail(request, book_slug, chapter_number):
    chapter_qs = Chapter.objects.filter(
        book__slug=book_slug).filter(chapter_number=chapter_number)
    chapter = chapter_qs[0]
    book_status = check_book_relationship(request, chapter.book)
    if chapter_qs.exists():
        context = {
            'chapter': chapter_qs[0],
            'book_status': book_status
        }
        return render(request, 'main/chapter_detail.html', context)
    return Http404


@login_required
def exercise_detail(request, book_slug, chapter_number, exercise_number):
    exercise_qs = Exercise.objects.filter(
        chapter__book__slug=book_slug).filter(chapter__chapter_number=chapter_number).filter(exercise_number=exercise_number)
    exercise = exercise_qs[0]
    book_status = check_book_relationship(request, exercise.chapter.book)
    if exercise_qs.exists():
        context = {
            'exercise': exercise_qs[0],
            'book_status': book_status
        }
        return render(request, 'main/exercise_detail.html', context)
    return Http404

main/templates/book_snippet.html
<h3> Book detail view </h3>
        <p>{{ book }}</p>
        <div class="card shadow-lg" style="width: 18rem;">
        <div class="card-header">{{ book.title }}</div>
        <img src="{{ book.cover.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <p class="card-text">Published: {{ book.publication }}</p>
        </div>
        {% if book_status != 'owned'%}
        <div class="card-footer">
        {% if book_status == 'in_cart' %}
            <a href="{% url 'cart:remove-from-cart' book.slug %}" class="btn btn-danger btn-block" >Remove from cart</a>
        {% else %}
            <a href="{% url 'cart:add-to-cart' book.slug %}" class="btn btn-warning btn-block" >Add to cart</a>
        {% endif %}
        </div>
        {% endif %}
        
        </div>

main/templates/main_base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Marketplace</title>
    {% load static %} 
    {% block css %} 
    {% block head_css_site %} 
    {% endblock head_css_site %} 
    {% endblock css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>

    <div class="container">

        {% include 'navbar.html' %}

        {% include 'messages.html' %}

            {% block breadcrumb %}
            
            {% endblock breadcrumb %}

        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

main/templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
{% endif %}

main/templates/navbar.html
{% load cart_template_tags %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'books:book-list' %}">Cloud Book Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse float-right" id="navbarSupportedContent" style="width:max-content; margin-left:750px;">
    <ul class="navbar-nav mr-auto">
    {% if request.user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:order-summary' %}">
        {{request.user|cart_item_count}}
        <i class="fa fa-shopping-cart"></i>
        </a>
      </li>
    {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
      </li>
    {% endif %}
      <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">Account<i class="fa fa-user"></i></a><li>
    </ul>
  </div>
</nav>

main/templates/old_base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>